import {num,esc,dateLabel} from './ui.js';
export function historyChart(rows,{unit='',cutoff='',projection=null,reveal=false}={}){
 const w=860,h=212,p={l:65,r:22,t:20,b:32};const values=rows.map(r=>r.close);if(projection)values.push(projection.price*(1+projection.lower/100),projection.price*(1+projection.upper/100));
 const low=Math.min(...values),high=Math.max(...values),pad=(high-low)*.15||low*.01||1,lo=low-pad,hi=high+pad,n=rows.length+(projection?7:0),x=i=>p.l+i/Math.max(1,n-1)*(w-p.l-p.r),y=v=>h-p.b-(v-lo)/(hi-lo)*(h-p.t-p.b);
 const cutoffIndex=rows.findLastIndex(r=>r.date<=cutoff);const path=(rs,start=0)=>rs.map((r,i)=>`${i?'L':'M'}${x(i+start)},${y(r.close)}`).join(' ');
 return `<div class="chart-wrap"><svg class="history-chart" viewBox="0 0 ${w} ${h}" role="group" aria-label="Simulated price history in ${esc(unit)} through ${cutoff}${reveal?'; subsequent outcomes revealed':''}" data-chart="price">
 ${[0,.25,.5,.75,1].map(t=>{const v=lo+(hi-lo)*t;return `<line class="gridline" x1="${p.l}" x2="${w-p.r}" y1="${y(v)}" y2="${y(v)}"/><text x="${p.l-10}" y="${y(v)+4}" text-anchor="end">${num(v,v<5?4:1)}</text>`;}).join('')}
 ${reveal?`<rect x="${x(cutoffIndex)}" y="${p.t}" width="${Math.max(0,x(rows.length-1)-x(cutoffIndex))}" height="${h-p.t-p.b}" fill="#EDB870" opacity=".045"/>`:''}
 <path d="${path(rows.slice(0,cutoffIndex+1))}" fill="none" stroke="#EDB870" stroke-width="2"/>
 ${reveal?`<path d="${path(rows.slice(cutoffIndex),cutoffIndex)}" fill="none" stroke="#8DA1AD" stroke-dasharray="4 5" stroke-width="2"/>`:''}
 ${projection?`<path d="M${x(cutoffIndex)},${y(projection.price)} L${x(n-1)},${y(projection.price*(1+projection.upper/100))} L${x(n-1)},${y(projection.price*(1+projection.lower/100))}Z" fill="#6ABEDB" opacity=".1"/><path d="M${x(cutoffIndex)},${y(projection.price)} L${x(n-1)},${y(projection.price*(1+projection.expected/100))}" stroke="#6ABEDB" stroke-width="2" stroke-dasharray="5 5"/>`:''}
 <line x1="${x(cutoffIndex)}" x2="${x(cutoffIndex)}" y1="${p.t}" y2="${h-p.b}" stroke="#EDB870" stroke-dasharray="3 5" opacity=".5"/><circle cx="${x(cutoffIndex)}" cy="${y(rows[cutoffIndex].close)}" r="4" fill="#EDB870"/>
 ${[0,Math.floor(cutoffIndex/2),cutoffIndex].filter((v,i,a)=>a.indexOf(v)===i).map(i=>`<text x="${x(i)}" y="${h-8}" text-anchor="middle">${rows[i].date.slice(5)}</text>`).join('')}
 <g class="crosshair" visibility="hidden"><line y1="${p.t}" y2="${h-p.b}" stroke="#E7EEF2" stroke-dasharray="2 3"/><circle r="4" fill="#E7EEF2"/></g>
 <rect class="chart-hit" x="${p.l}" y="${p.t}" width="${w-p.l-p.r}" height="${h-p.t-p.b}" fill="transparent" tabindex="0" role="slider" aria-label="Inspect historical price; use arrow keys" aria-valuemin="0" aria-valuemax="${rows.length-1}" aria-valuenow="${cutoffIndex}" data-rows="${esc(JSON.stringify(rows.map(r=>({date:r.date,close:r.close}))))}" data-n="${n}" data-lo="${lo}" data-hi="${hi}" data-unit="${esc(unit)}"/>
 </svg><div class="chart-readout" aria-live="polite">${dateLabel(cutoff)} · ${num(rows[cutoffIndex].close,unit==='USD / EUR'?4:2)} ${esc(unit)}${reveal?' · EVALUATION: subsequent outcomes visible':''}</div></div>`;
}
export function equityChart(curve){const rows=curve.length?curve:[];if(!rows.length)return '<div class="empty">Advance replay one day to inspect portfolio returns.</div>';const w=1000,h=265,lo=Math.min(...rows.flatMap(r=>[r.equity,r.benchmark]))*.99,hi=Math.max(...rows.flatMap(r=>[r.equity,r.benchmark]))*1.01;const y=v=>225-(v-lo)/(hi-lo)*205,x=i=>70+i/(rows.length-1||1)*905;return `<svg viewBox="0 0 ${w} ${h}" class="equity-chart" role="img" aria-label="Simulated strategy equity ${num(rows.at(-1).equity)} USD versus buy and hold ${num(rows.at(-1).benchmark)} USD">${[0,.5,1].map(t=>`<line class="gridline" x1="70" x2="975" y1="${y(lo+(hi-lo)*t)}" y2="${y(lo+(hi-lo)*t)}"/><text x="58" y="${y(lo+(hi-lo)*t)+4}" text-anchor="end">${num((lo+(hi-lo)*t)/1000,1)}k</text>`).join('')}${['benchmark','equity'].map(k=>`<path d="${rows.map((r,i)=>`${i?'L':'M'}${x(i)},${y(r[k])}`).join(' ')}" fill="none" stroke="${k==='equity'?'#59D6AE':'#8DA1AD'}" stroke-width="2" ${k==='benchmark'?'stroke-dasharray="5 5"':''}/>`).join('')}<text x="70" y="252">${rows[0].date}</text><text x="975" y="252" text-anchor="end">${rows.at(-1).date}</text></svg>`;}
export function bindCharts(root){root.querySelectorAll('.chart-hit').forEach(hit=>{const rows=JSON.parse(hit.dataset.rows),svg=hit.ownerSVGElement,g=svg.querySelector('.crosshair');let selected=Number(hit.getAttribute('aria-valuenow'));function show(i){selected=Math.max(0,Math.min(rows.length-1,i));const row=rows[selected],x=65+selected/Math.max(1,Number(hit.dataset.n)-1)*773,y=180-(row.close-Number(hit.dataset.lo))/(Number(hit.dataset.hi)-Number(hit.dataset.lo))*160;g.setAttribute('visibility','visible');g.querySelector('line').setAttribute('x1',x);g.querySelector('line').setAttribute('x2',x);g.querySelector('circle').setAttribute('cx',x);g.querySelector('circle').setAttribute('cy',y);hit.setAttribute('aria-valuenow',selected);hit.setAttribute('aria-valuetext',`${row.date}: ${row.close}`);svg.parentElement.querySelector('.chart-readout').textContent=`${dateLabel(row.date)} · ${num(row.close,4)} ${hit.dataset.unit} · Simulated observation`;}
 hit.addEventListener('pointermove',e=>{const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const local=pt.matrixTransform(svg.getScreenCTM().inverse());show(Math.round((local.x-65)/773*(Number(hit.dataset.n)-1)));});hit.addEventListener('focus',()=>show(selected));hit.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();show(selected+(e.key==='ArrowRight'?1:-1));}});
 });}
