import {esc} from './ui.js';
const project=([lon,lat])=>[(lon-62)*10,(49-lat)*9];
let landPath='';
function geometryPath(geometry){if(geometry.type==='GeometryCollection')return geometry.geometries.map(geometryPath).join(' ');const polygons=geometry.type==='Polygon'?[geometry.coordinates]:geometry.type==='MultiPolygon'?geometry.coordinates:[];return polygons.flatMap(p=>p.map(r=>r.map((c,i)=>`${i?'L':'M'}${project(c).map(v=>v.toFixed(1)).join(',')}`).join(' ')+'Z')).join(' ');}
export function mapView(repo,state,date){
 if(!landPath)landPath=(repo.geography.features||[{geometry:repo.geography}]).map(f=>geometryPath(f.geometry)).join(' ');
 const zoom=state.zoom,w=900/zoom,h=510/zoom,vx=450-w/2,vy=255-h/2;
 const routePath=r=>{const [a,b,c]=[r.from,r.via,r.to].map(project);return `M${a} Q${b} ${c}`;};
 const vesselPoint=v=>{const r=repo.raw.routes.find(r=>r.id===v.route_id);if(!r)return null;const t=v.progress;return project([0,1].map(i=>(1-t)**2*r.from[i]+2*(1-t)*t*r.via[i]+t*t*r.to[i]));};
 return `<section class="panel map-panel"><div class="panel-head"><div><span class="eyebrow">GEOGRAPHIC CONTEXT</span><h2>Indo-Pacific supply network</h2></div><span class="metadata">${repo.raw.locations.length} LOCATIONS / DAILY OBSERVATIONS</span></div><div class="map-toolbar">${['supply','ocean','vessels'].map(k=>`<label class="layer ${k}"><input type="checkbox" data-layer="${k}" ${state.layers[k]?'checked':''}><span>${k[0].toUpperCase()+k.slice(1)}</span></label>`).join('')}<span class="map-date">${date}</span></div>
 <div class="map-canvas"><svg viewBox="${vx} ${vy} ${w} ${h}" role="group" aria-label="Indo-Pacific synthetic research map. Select a station, supply hub or fictional vessel."><defs><pattern id="map-grid" width="100" height="90" patternUnits="userSpaceOnUse"><path d="M100 0H0V90" fill="none" stroke="#263038" stroke-width=".55"/></pattern></defs><rect x="-3000" y="-1500" width="6000" height="4000" fill="#0d141a"/><rect x="-3000" y="-1500" width="6000" height="4000" fill="url(#map-grid)"/><path d="${landPath}" fill="#192229" stroke="#38434b" stroke-width=".8"/>
 ${[[79,25,'INDIA'],[106,35,'CHINA'],[139,39,'JAPAN'],[101,19,'THAILAND'],[118,-3,'INDONESIA']].map(([lon,lat,label])=>{const [x,y]=project([lon,lat]);return `<text class="country" x="${x}" y="${y}">${label}</text>`;}).join('')}
 <text class="ocean-label" x="160" y="440">INDIAN OCEAN</text><text class="ocean-label" x="720" y="305">PACIFIC OCEAN</text>
 ${state.layers.vessels?repo.raw.routes.map(r=>`<path d="${routePath(r)}" fill="none" stroke="#b0a18b" stroke-width="1" stroke-dasharray="3 5" opacity=".7"><title>${esc(r.name)} — illustrative demo route</title></path>`).join(''):''}
 ${repo.raw.locations.filter(l=>state.layers[l.kind]).map(l=>{const [x,y]=project([l.lon,l.lat]),selected=state.selection?.id===l.id,obs=selected?repo.getObservations(l.id,date).at(-1):null;return `<g tabindex="0" role="button" data-location="${l.id}" aria-label="${esc(l.name)}, ${l.kind==='supply'?'supply hub':'ocean observation station'}" class="map-marker ${l.kind} ${selected?'selected':''}"><title>${esc(l.name)} · ${l.kind} · select to inspect synthetic observations</title><circle cx="${x}" cy="${y}" r="17" fill="transparent"/>${selected?`<path d="M${x-22},${y}h10m24 0h10M${x},${y-22}v10m0 24v10" fill="none" stroke="currentColor" opacity=".65"/><circle cx="${x}" cy="${y}" r="14" fill="none" stroke="currentColor" opacity=".6"/>`:''}${l.kind==='supply'?`<rect x="${x-4}" y="${y-4}" width="8" height="8" fill="currentColor" transform="rotate(45 ${x} ${y})"/>`:`<circle cx="${x}" cy="${y}" r="4" fill="#0d141a" stroke="currentColor" stroke-width="2"/>`}${selected&&obs?`<g class="map-annotation" transform="translate(${Math.min(725,Math.max(15,x-161))} ${y-54})"><rect width="149" height="39" fill="#111a21" stroke="#647077" stroke-width=".65"/><text x="9" y="14">${esc(l.name.split(' ')[0].toUpperCase())} / ${l.id}</text><text x="9" y="29" class="annotation-value">${l.kind==='supply'?'Inventory '+obs.inventory_index:obs.temperature_c+' °C'} · ${obs.reporting_delay_hours}h delay</text></g>`:''}${l.kind==='supply'&&l.id!=='S10'?`<text x="${x+12}" y="${y-11}">${esc(l.name.split(' ')[0])}</text>`:''}</g>`;}).join('')}
 ${state.layers.vessels?repo.getVessels(date).map(v=>{const point=vesselPoint(v);if(!point)return '';const [x,y]=point;return `<g tabindex="0" role="button" data-vessel="${v.id}" aria-label="Fictional vessel ${esc(v.name)}" class="map-marker vessel"><title>${esc(v.name)} · ${v.speed_kn} kn · fictional vessel</title><circle cx="${x}" cy="${y}" r="12" fill="transparent"/><path d="M${x} ${y-5}l4 10-4-2-4 2Z" fill="currentColor"/></g>`;}).join(''):''}
 </svg><div class="zoom-controls"><button data-action="zoom-in" aria-label="Zoom in" ${zoom>=2.5?'disabled':''}>+</button><button data-action="zoom-out" aria-label="Zoom out" ${zoom<=.8?'disabled':''}>−</button><button data-action="zoom-reset" aria-label="Reset map extent">↗</button></div><span class="map-coordinate">62° E — 152° E<br>49° N — 8° S · INITIAL EXTENT</span></div>
 <div class="map-legend"><span><i class="legend-supply"></i>Supply hub</span><span><i class="legend-ocean"></i>Ocean station</span><span><i class="legend-vessel"></i>Fictional vessel</span><span><i class="legend-route"></i>Illustrative route</span><small>Natural Earth geography</small></div></section>`;
}
