import {esc,num,pct,tone,spark,dateLabel} from '../components/ui.js';
import {mapView} from '../components/map.js';
import {historyChart} from '../components/charts.js';
export function watchRows(repo,state,date){const assets=repo.getAssets().filter(a=>(a.id+' '+a.name+' '+a.category).toLowerCase().includes(state.search.toLowerCase()));return ['Goldfish','Equities','FX'].map(category=>{const group=assets.filter(a=>a.category===category);return group.length?`<div class="group-title">${category}<span>${group.length.toString().padStart(2,'0')}</span></div>${group.map(a=>{const rows=repo.getMarketHistory(a.id,date),last=rows.at(-1),prev=rows.at(-2)||last,change=(last.close/prev.close-1)*100;return `<button class="instrument ${a.id===state.asset?'selected':''}" data-asset="${a.id}" aria-pressed="${a.id===state.asset}"><span class="instrument-top"><strong>${a.id}</strong><b>${num(last.close,a.category==='FX'?4:2)}</b></span><span class="instrument-name">${esc(a.name)}${category==='Equities'?' · fictional':''}</span><span class="instrument-bottom"><span class="${tone(change)}">${pct(change)}</span><span class="${tone(change)}">${spark(rows.slice(-28))}</span></span><span class="unit">${a.unit}${category==='Goldfish'?' · '+(repo.raw.transactions.find(t=>t.asset_id===a.id)?.grade||'fixed grade'):''}</span></button>`;}).join('')}`:'';}).join('')||'<div class="empty">No matching instruments.</div>';}
export function contributions(s){const max=Math.max(...s.factors.map(f=>Math.abs(f.contribution)),.001);return `<div class="contributions">${s.factors.map(f=>`<div class="factor"><div><span>${f.label}</span><b class="${tone(f.contribution)}">${f.enabled?(f.contribution>=0?'+':'')+num(f.contribution*100,3)+' pp':'Disabled'}</b></div><div class="diverging"><i style="left:${f.contribution<0?50-Math.abs(f.contribution)/max*48:50}%;width:${Math.abs(f.contribution)/max*48}%;background:${f.contribution<0?'var(--coral)':'var(--mint)'}"></i></div></div>`).join('')}<small>Daily return contributions · percentage points<br>Engine attribution, not causal effects.</small></div>`;}
export function signalInspector(repo,state,asset,s,date){const selection=state.selection;let detail='';if(selection){const l=repo.raw.locations.find(l=>l.id===selection.id),v=repo.getVessels(date).find(v=>v.id===selection.id);if(l){const obs=repo.getObservations(l.id,date).at(-1);const fields=l.kind==='supply'?[['Inventory index',obs?.inventory_index,'index points']]:[['Temperature',obs?.temperature_c,'°C'],['Salinity',obs?.salinity_psu,'PSU'],['Current speed',obs?.current_ms,'m/s'],['Chlorophyll',obs?.chlorophyll_mgm3,'mg/m³']];detail=`<span class="eyebrow">${l.kind==='supply'?'SUPPLY HUB':'OCEAN OBSERVATION STATION'}</span><h3>${esc(l.name)}</h3><p class="muted">${l.region} · ${obs?.date||'No observations'}</p>${fields.map(([label,val,unit])=>`<div class="detail-row"><span>${label}</span><b>${val??'Unavailable'} <small>${unit}</small></b></div>`).join('')}<div class="detail-row"><span>Reporting delay</span><b>${obs?.reporting_delay_hours??'—'} h</b></div><div class="detail-row"><span>Quality</span><b>${obs?.quality??'Missing'}</b></div><p class="footnote">Synthetic fixture v${repo.raw.manifest.version}. Dates are daily buckets; publication timestamps are unavailable. ${l.kind==='ocean'?'Ocean stations do not measure breeder inventory.':'Inventory is a synthetic supply observation, not an ocean measurement.'}</p>`;}else if(v){detail=`<span class="eyebrow">FICTIONAL VESSEL</span><h3>${esc(v.name)}</h3><p class="muted">${date} · ${v.id}</p>${[['Route',v.route_id],['Speed',v.speed_kn+' kn'],['Delay',v.delay_hours+' h'],['Route progress',num(v.progress*100,1)+'%']].map(([k,val])=>`<div class="detail-row"><span>${k}</span><b>${val}</b></div>`).join('')}<p class="footnote">Synthetic position interpolated along an illustrative route at the replay date. No AIS connection.</p>`;}}
 const enabled=s.factors.filter(f=>f.enabled&&f.contribution!==0);const dominant=[...enabled].sort((a,b)=>Math.abs(b.contribution)-Math.abs(a.contribution))[0];const explain=dominant?`${dominant.id==='supply'?(dominant.value>0?'Lower synthetic breeder inventory':'Higher synthetic breeder inventory'):dominant.label} is the largest ${dominant.contribution>0?'positive':'negative'} contributor (${dominant.contribution>=0?'+':''}${num(dominant.contribution*100,3)} pp per day).`:'All data groups are disabled. The deterministic projection is flat.';
 return `<aside class="inspector"><section class="panel signal-panel"><div class="panel-head"><span class="eyebrow">MODEL OUTPUT</span><span class="metadata">07D</span></div><div class="signal-title"><h2>${asset.id}</h2><span class="stance ${tone(s.expected)}">${s.stance}</span></div><p class="muted">Simulated research signal</p><div class="projection-value ${tone(s.expected)}">${pct(s.expected)}<span>Scenario-projected change</span></div><div class="scenario-tag">${state.scenario==='baseline'?'Baseline assumption':state.scenario.toUpperCase()+' · INJECTED SCENARIO'}</div><h3 class="section-label">Input contributions</h3>${contributions(s)}<p class="explanation">${explain}</p><div class="cutoff"><span>Data cutoff</span><b>${date} · EOD</b></div><details class="assumptions"><summary>Input availability & methodology</summary><p class="footnote">Engine inputs: daily engineered factors; all three values available. Station reporting delays are metadata, not applied by this toy engine. No training run or validated predictive accuracy.</p></details><button class="wide" data-action="export-signal">Export snapshot <span aria-hidden="true">↓</span></button></section><section class="panel observation-panel"><div class="panel-head"><span class="eyebrow">OBSERVATION DETAIL</span>${selection?'<button class="text-button" data-action="clear-selection" aria-label="Clear map selection">×</button>':''}</div>${detail||'<div class="empty"><h3>No observation selected</h3><p>Select a supply hub, ocean station or vessel on the map to inspect its observations.</p></div>'}</section></aside>`;
}
export function intelligence(repo,state,asset,s,date){
 const rows=repo.getMarketHistory(asset.id,state.reveal?repo.raw.days.at(-1).date:date);
 const events=repo.getEvents(date).slice(-4).reverse();
 const eventStream=`<section class="events-panel"><div class="panel-head"><h2>Context events</h2><span class="metadata">${events.length}</span></div><p class="event-hint">Select an event to inspect its location.</p>${events.length?events.map(e=>`<button class="event-row" data-location="${e.location_id}" title="${esc(e.detail)}"><span class="event-date">${e.date.slice(5)}</span><span class="event-copy"><strong>${esc(e.title)}</strong><small>${esc(repo.raw.locations.find(l=>l.id===e.location_id)?.name)}</small><small class="event-description">${esc(e.detail)}</small></span><span class="event-severity ${e.severity==='elevated'?'amber':''}">${e.severity}</span></button>`).join(''):'<div class="empty">No events available at this cutoff.</div>'}</section>`;
 return `<div class="intelligence-layout">
 <aside class="watchlist panel"><div class="watch-header"><h2>Instruments</h2><span class="metadata">${repo.raw.assets.length.toString().padStart(2,'0')}</span></div><label class="search"><svg viewBox="0 0 20 20" aria-hidden="true"><circle cx="8" cy="8" r="5"/><path d="m12 12 5 5"/></svg><input type="search" id="instrument-search" placeholder="Search universe" value="${esc(state.search)}" aria-label="Search instruments"></label><div id="watch-rows">${watchRows(repo,state,date)}</div>${eventStream}<div class="watch-footer">SYNTHETIC MARKET UNIVERSE<br><span>Completed sales · fictional equities · FX</span></div></aside>
 <div class="research-main"><div class="instrument-heading"><div><span class="eyebrow">${asset.category.toUpperCase()} <span class="heading-divider">/</span> ${asset.id}</span><h1>${asset.name}</h1><p>${esc(asset.description)}</p></div><div class="current-price"><span class="price-label">${asset.category==='Goldfish'?'COMPLETED-SALE PRICE':'SYNTHETIC CLOSE'}</span><strong>${num(s.price,asset.category==='FX'?4:2)}</strong><span>${asset.unit} <b class="${tone(s.change)}">${pct(s.change)}</b></span></div></div>
 ${mapView(repo,state,date)}
 <section class="panel history-panel"><div class="panel-head"><div><h2>Price history <span class="metadata">${asset.unit}</span></h2></div><div class="chart-options"><label><input type="checkbox" data-setting="projection" ${state.projection?'checked':''} ${state.reveal?'disabled':''}> Scenario projection</label><label class="${state.reveal?'amber':''}"><input type="checkbox" data-setting="reveal" ${state.reveal?'checked':''}> Reveal subsequent outcome</label></div></div>${historyChart(rows,{unit:asset.unit,cutoff:date,projection:state.projection&&!state.reveal?s:null,reveal:state.reveal})}${state.projection&&!state.reveal?'<p class="chart-note">Dashed cyan: seven-day scenario projection. The engine band is not a calibrated confidence interval.</p>':''}</section><div class="mobile-events">${eventStream}</div></div>
 ${signalInspector(repo,state,asset,s,date)}</div>`;
}
